### ISSUE TITLE
Link to the sample config is no longer working.

### ISSUE THREAD

**Issue by makmarius** [signalfx/collectd-rabbitmq#21]
As the title says, the link to the sample config in the Readme is no longer pointing to the correct destination.

**Comment by flands** [comment]
Correct link appears to be https://github.com/signalfx/integrations/blob/master/rabbitmq/10-rabbitmq.conf

**Comment by flands** [comment]
Fixed in https://github.com/signalfx/collectd-rabbitmq/pull/22
